[1,"Error occurred during cleanup: Error: The process cannot access the file because it is being used by another process. (os error 32): remove 'C:\\Users\\liem2\\AppData\\Local\\Temp\\quarto-sessiond9d7580c04fc3f0f'\n"]
